### ISSUE TITLE
New version with github.com/go-jose/go-jose/v3 from 3.0.0 to 3.0.1

### ISSUE THREAD

**Issue by Vandborg** [qvik/go-oidc-mle#15]
Hi Janne

Thanks for this lib. I can see you already bumped github.com/go-jose/go-jose/v3 from 3.0.0 to 3.0.1 which fixes an known vulnerability. Could I get you to make a new release with this? :)

https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMGOJOSEGOJOSEV3-6070737

**Comment by haaja** [comment]
Thanks for the report. [Here](https://github.com/qvik/go-oidc-mle/releases/tag/v0.0.8) you go.
